Repository mariacmaruch/pratico_2_gces, pull requests merged in 2023-02, with the labels that each got.

#2 Update readme.md
  readme.md
Labels: documentation

#1 alteraçao linha 2
  readme.md
Labels: bug

#8 quicksort
  quicksort.java
Labels: enhancement

#10 Update readme.md
  readme.md
Labels: bug
